// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesHub.Services.ReviewsAPI.Data;

#nullable disable

namespace MoviesHub.Services.ReviewsAPI.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    partial class ReviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesHub.Services.ReviewsAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasAnnotation("MaxValue", 10)
                        .HasAnnotation("MinValue", 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "The Dark Knight redefines what a superhero movie can be.",
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 1,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Inception bends your mind with its dream concept.",
                            CreatedAt = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 2,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Mad Max delivers non-stop adrenaline with its spectacular practical effects.",
                            CreatedAt = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 3,
                            Rating = 8,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "John Wick revolutionized action choreography. Keanu Reeves at his best.",
                            CreatedAt = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 4,
                            Rating = 10,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "The Avengers set the standard for team-up superhero movies.",
                            CreatedAt = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 5,
                            Rating = 8,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Black Panther's cultural significance matches its cinematic excellence.",
                            CreatedAt = new DateTime(2023, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 6,
                            Rating = 10,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Superbad captures teenage awkwardness perfectly. Endlessly quotable.",
                            CreatedAt = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 7,
                            Rating = 8,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "The Hangover created a new template for raunchy comedies.",
                            CreatedAt = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 8,
                            Rating = 8,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Bridesmaids proves women can headline hilarious R-rated comedies.",
                            CreatedAt = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 9,
                            Rating = 8,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Deadpool breaks the fourth wall with perfect comedic timing.",
                            CreatedAt = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 10,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Wes Anderson's signature style shines in Grand Budapest Hotel.",
                            CreatedAt = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 11,
                            Rating = 10,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Booksmart is the smart, heartfelt teen comedy we needed.",
                            CreatedAt = new DateTime(2023, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 12,
                            Rating = 8,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "The Social Network's razor-sharp dialogue makes tech history thrilling.",
                            CreatedAt = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 13,
                            Rating = 10,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "12 Years a Slave is a brutal, essential American story.",
                            CreatedAt = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 14,
                            Rating = 10,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Parasite masterfully blends genres while delivering social commentary.",
                            CreatedAt = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 15,
                            Rating = 10,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "La La Land's magical realism makes it an instant classic.",
                            CreatedAt = new DateTime(2023, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 16,
                            Rating = 10,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "The King's Speech proves great acting can make any subject compelling.",
                            CreatedAt = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 17,
                            Rating = 8,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Moonlight's intimate storytelling is profoundly moving.",
                            CreatedAt = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 18,
                            Rating = 7,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Get Out blends horror and social satire perfectly.",
                            CreatedAt = new DateTime(2023, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 19,
                            Rating = 9,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Hereditary builds dread like few modern horror films.",
                            CreatedAt = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 20,
                            Rating = 8,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 21,
                            Comment = "A Quiet Place's sound design creates incredible tension.",
                            CreatedAt = new DateTime(2023, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 21,
                            Rating = 8,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 22,
                            Comment = "The Conjuring sets new standards for supernatural horror.",
                            CreatedAt = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 22,
                            Rating = 8,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 23,
                            Comment = "It revitalizes Stephen King adaptations with great scares.",
                            CreatedAt = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 23,
                            Rating = 8,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 24,
                            Comment = "The Babadook uses horror to explore grief brilliantly.",
                            CreatedAt = new DateTime(2023, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 24,
                            Rating = 8,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Interstellar's cosmic ambition matches its emotional depth.",
                            CreatedAt = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 25,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Arrival's linguistic sci-fi approach is refreshingly original.",
                            CreatedAt = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 26,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Blade Runner 2049 lives up to the original's legacy.",
                            CreatedAt = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 27,
                            Rating = 10,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 28,
                            Comment = "The Martian makes science exciting and accessible.",
                            CreatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 28,
                            Rating = 8,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Ex Machina offers a chilling look at AI.",
                            CreatedAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 29,
                            Rating = 10,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Gravity is a visually stunning survival story.",
                            CreatedAt = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 30,
                            Rating = 8,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Mad Max: Fury Road redefines the action genre with relentless energy.",
                            CreatedAt = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 31,
                            Rating = 10,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 32,
                            Comment = "John Wick delivers stylish and intense action sequences.",
                            CreatedAt = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 32,
                            Rating = 8,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 33,
                            Comment = "The Dark Knight blends superhero action with crime drama brilliantly.",
                            CreatedAt = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 33,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Inception is an action-packed dreamscape like no other.",
                            CreatedAt = new DateTime(2023, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 34,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Skyfall delivers Bond's emotional depth with thrilling spectacle.",
                            CreatedAt = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 35,
                            Rating = 8,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 36,
                            Comment = "The Raid redefines close-quarters action choreography.",
                            CreatedAt = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 36,
                            Rating = 8,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Inside Out is a masterclass in emotional storytelling.",
                            CreatedAt = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 37,
                            Rating = 10,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Spider-Man: Into the Spider-Verse innovates animation and superhero films.",
                            CreatedAt = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 38,
                            Rating = 10,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Coco is a vibrant, heartfelt celebration of family and culture.",
                            CreatedAt = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 39,
                            Rating = 10,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Zootopia blends clever social commentary with adorable animation.",
                            CreatedAt = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 40,
                            Rating = 8,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Toy Story 3 delivers nostalgia and deep emotional impact.",
                            CreatedAt = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 41,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Frozen charms with its memorable songs and strong characters.",
                            CreatedAt = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 42,
                            Rating = 8,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 43,
                            Comment = "The Grand Budapest Hotel is a visually delightful comedic adventure.",
                            CreatedAt = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 43,
                            Rating = 8,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 44,
                            Comment = "21 Jump Street is a hilarious and smart reboot.",
                            CreatedAt = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 44,
                            Rating = 8,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Bridesmaids brings heartfelt humor with a brilliant ensemble cast.",
                            CreatedAt = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 45,
                            Rating = 8,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 46,
                            Comment = "The Hangover delivers outrageous laughs and unforgettable moments.",
                            CreatedAt = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 46,
                            Rating = 8,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Superbad captures teenage awkwardness with hilarious accuracy.",
                            CreatedAt = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 47,
                            Rating = 8,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Borat offers biting satire through its outrageous humor.",
                            CreatedAt = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 48,
                            Rating = 8,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Moonlight is a profound coming-of-age story with stunning performances.",
                            CreatedAt = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 49,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 50,
                            Comment = "The Social Network brilliantly captures the rise of Facebook.",
                            CreatedAt = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 50,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 51,
                            Comment = "La La Land dazzles with its nostalgic love story and music.",
                            CreatedAt = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 51,
                            Rating = 8,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Whiplash is an electrifying portrayal of ambition and obsession.",
                            CreatedAt = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 52,
                            Rating = 10,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 53,
                            Comment = "The King's Speech is a stirring historical drama with powerful performances.",
                            CreatedAt = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 53,
                            Rating = 8,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Slumdog Millionaire is an uplifting tale of love and destiny.",
                            CreatedAt = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 54,
                            Rating = 8,
                            UserId = "8"
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Gone Girl is a chilling, twisty psychological thriller.",
                            CreatedAt = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 55,
                            Rating = 8,
                            UserId = "9"
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Prisoners is a dark and gripping morality tale.",
                            CreatedAt = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 56,
                            Rating = 10,
                            UserId = "10"
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Nightcrawler is a haunting dive into media ethics and ambition.",
                            CreatedAt = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 57,
                            Rating = 10,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Shutter Island keeps audiences guessing until the end.",
                            CreatedAt = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 58,
                            Rating = 10,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 59,
                            Comment = "The Girl with the Dragon Tattoo is a chilling and complex mystery.",
                            CreatedAt = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 59,
                            Rating = 10,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Sicario delivers unrelenting tension and stark moral ambiguity.",
                            CreatedAt = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 60,
                            Rating = 10,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 61,
                            Comment = "A fun return for Indiana Jones with exciting action sequences and nostalgic charm.",
                            CreatedAt = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 61,
                            Rating = 8,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 62,
                            Comment = "The Rock and Emily Blunt have great chemistry in this entertaining adventure inspired by the Disney ride.",
                            CreatedAt = new DateTime(2021, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 62,
                            Rating = 8,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 63,
                            Comment = "Sandra Bullock and Channing Tatum make a hilarious duo in this jungle romp that doesn't take itself too seriously.",
                            CreatedAt = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 63,
                            Rating = 6,
                            UserId = "5"
                        },
                        new
                        {
                            Id = 64,
                            Comment = "Tom Holland brings his charm to this video game adaptation with plenty of treasure-hunting action.",
                            CreatedAt = new DateTime(2022, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 64,
                            Rating = 6,
                            UserId = "6"
                        },
                        new
                        {
                            Id = 65,
                            Comment = "A surprisingly fun live-action adaptation that works for both kids and adults.",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 65,
                            Rating = 8,
                            UserId = "7"
                        },
                        new
                        {
                            Id = 66,
                            Comment = "Ryan Reynolds shines in this heartfelt time-travel adventure with great action and humor.",
                            CreatedAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MovieId = 66,
                            Rating = 8,
                            UserId = "8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
