// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesHub.Services.MoviesAPI.Data;

#nullable disable

namespace MoviesHub.Services.MoviesAPI.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250413020828_InitialCreateAndSeed")]
    partial class InitialCreateAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Anime"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AverageRating");

                    b.HasIndex("ReleaseYear");

                    b.HasIndex("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 9.0m,
                            CreatedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the menace known as the Joker wreaks havoc...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 8.8m,
                            CreatedAt = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thief who steals corporate secrets...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2015,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 7.4m,
                            CreatedAt = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Earth's mightiest heroes must come together and learn to fight as a team...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2012,
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 7.3m,
                            CreatedAt = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "T'Challa, heir to the hidden but advanced kingdom of Wakanda...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 7.6m,
                            CreatedAt = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two co-dependent high school seniors are forced to deal with separation anxiety...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTc0NjIyMjA2OF5BMl5BanBnXkFtZTcwMzIxNDE1MQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2007,
                            Title = "Superbad"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2020, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Three buddies wake up from a bachelor party in Las Vegas...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2009,
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 6.8m,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Competition between the maid of honor and a bridesmaid...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjAyOTMyMzUxNl5BMl5BanBnXkFtZTcwODI4MzE0NA@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2011,
                            Title = "Bridesmaids"
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A wisecracking mercenary gets experimented on and becomes immortal...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "Deadpool"
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The adventures of Gustave H, a legendary concierge at a famous hotel...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 7.1m,
                            CreatedAt = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "On the eve of their high school graduation, two academic superstars...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzBhYmMzYWQtZTMzMS00YjNkLWE4ODItOGM5YWJlY2E1YTI1XkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2019,
                            Title = "Booksmart"
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Harvard student Mark Zuckerberg creates the social networking site...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In the antebellum United States, Solomon Northup is kidnapped and sold into slavery...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2013,
                            Title = "12 Years a Slave"
                        },
                        new
                        {
                            Id = 15,
                            AverageRating = 8.6m,
                            CreatedAt = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 16,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "While navigating their careers in Los Angeles, a pianist and an actress...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 17,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "King George VI struggles with a stammer and seeks help from an unorthodox speech therapist...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "The King's Speech"
                        },
                        new
                        {
                            Id = 18,
                            AverageRating = 7.4m,
                            CreatedAt = new DateTime(2021, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young African-American man grapples with his identity and sexuality...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "Moonlight"
                        },
                        new
                        {
                            Id = 19,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2021, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young African-American visits his white girlfriend's parents for the weekend...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 7.3m,
                            CreatedAt = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A grieving family is haunted by tragic and disturbing occurrences...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Title = "Hereditary"
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 7.5m,
                            CreatedAt = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a post-apocalyptic world, a family must live in silence to avoid creatures...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 7.5m,
                            CreatedAt = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2013,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 7.3m,
                            CreatedAt = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "It"
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 6.8m,
                            CreatedAt = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A single mother and her child fall into a deep well of paranoia when an eerie children's book...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTk0NzMzODc2NF5BMl5BanBnXkFtZTgwNTY5NTM1NjE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "The Babadook"
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 8.6m,
                            CreatedAt = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 7.9m,
                            CreatedAt = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A linguist is recruited by the military to communicate with alien lifeforms...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "Arrival"
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2015,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "Ex Machina"
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 7.9m,
                            CreatedAt = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An extraterrestrial race forced to live in slum-like conditions on Earth suddenly finds a kindred spirit...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYmY5MzJiN2UtZDFmNi00YzhjLThjNmUtMTEwZDIzYjVlY2YxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2009,
                            Title = "District 9"
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 8.4m,
                            CreatedAt = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Title = "Spider-Man: Into the Spider-Verse"
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 8.4m,
                            CreatedAt = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "Coco"
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 8.0m,
                            CreatedAt = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "Zootopia"
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 7.4m,
                            CreatedAt = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2013,
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An ordinary Lego construction worker, thought to be the prophesied 'Special', is recruited to join a quest...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTg4MDk1ODExN15BMl5BanBnXkFtZTgwNzIyNjg3MDE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "The Lego Movie"
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "How to Train Your Dragon"
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 8.4m,
                            CreatedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "Your Name"
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 8.6m,
                            CreatedAt = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2001,
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young man is ostracized by his classmates after he bullies a deaf girl to the point where she leaves...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZGRkOGMxYTUtZTBhYS00NzI3LWEzMDQtOWRhMmNjNjJjMzM4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2016,
                            Title = "A Silent Voice"
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 7.5m,
                            CreatedAt = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A high-school boy who has run away to Tokyo befriends a girl who appears to be able to manipulate the weather...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNzBmMWE1ODYtY2Q5YS00Y2NiLWI3Y2QtYjI0NGE0OTBlY2E2XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2019,
                            Title = "Weathering With You"
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 8.4m,
                            CreatedAt = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 1997,
                            Title = "Princess Mononoke"
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 8.3m,
                            CreatedAt = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamado's journey...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BODI2NjdlYWItMTE1ZC00YzI2LTlhZGQtNzE3NzYxMTc0ZmVkXkEyXkFqcGdeQXVyNjU1OTg4OTM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2020,
                            Title = "Demon Slayer: Mugen Train"
                        },
                        new
                        {
                            Id = 43,
                            AverageRating = 7.8m,
                            CreatedAt = new DateTime(2023, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2004,
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 44,
                            AverageRating = 8.3m,
                            CreatedAt = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When their relationship turns sour, a couple undergoes a procedure to have each other erased from their memories...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2004,
                            Title = "Eternal Sunshine of the Spotless Mind"
                        },
                        new
                        {
                            Id = 45,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZDdiZTAwYzAtMDI3Ni00OTRjLTkzN2UtMGE3MDMyZmU4NTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 1995,
                            Title = "Before Sunrise"
                        },
                        new
                        {
                            Id = 46,
                            AverageRating = 6.9m,
                            CreatedAt = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This contemporary romantic comedy, based on a global bestseller, follows native New Yorker Rachel Chu...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTYxNDMyOTAxN15BMl5BanBnXkFtZTgwMDg1ODYzNTM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Title = "Crazy Rich Asians"
                        },
                        new
                        {
                            Id = 47,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2012,
                            Title = "Silver Linings Playbook"
                        },
                        new
                        {
                            Id = 48,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After being dumped by the girl he believes to be his soulmate, hopeless romantic Tom Hansen reflects...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTk5MjM4OTU1OV5BMl5BanBnXkFtZTcwODkzNDIzMw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2009,
                            Title = "500 Days of Summer"
                        },
                        new
                        {
                            Id = 49,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 50,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2013,
                            Title = "Prisoners"
                        },
                        new
                        {
                            Id = 51,
                            AverageRating = 7.9m,
                            CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "Nightcrawler"
                        },
                        new
                        {
                            Id = 52,
                            AverageRating = 7.7m,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2UwNDc5NmEtNjVjZS00OTI5LWE5YjctMWM3ZjBiZGYwMGI2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2007,
                            Title = "Zodiac"
                        },
                        new
                        {
                            Id = 53,
                            AverageRating = 7.8m,
                            CreatedAt = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTczNDk4NTQ0OV5BMl5BanBnXkFtZTcwNDAxMDgxNw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2011,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 54,
                            AverageRating = 8.2m,
                            CreatedAt = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = 55,
                            AverageRating = 8.8m,
                            CreatedAt = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2001,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 56,
                            AverageRating = 8.2m,
                            CreatedAt = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTU3ODg2NjQ5NF5BMl5BanBnXkFtZTcwMDEwODgzMQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2006,
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            Id = 57,
                            AverageRating = 7.6m,
                            CreatedAt = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a countryside town bordering on a magical land, a young man makes a promise to his beloved...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjkyMTE1OTYwNF5BMl5BanBnXkFtZTcwMDIxODYzMw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2007,
                            Title = "Stardust"
                        },
                        new
                        {
                            Id = 58,
                            AverageRating = 7.3m,
                            CreatedAt = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGNiNWQ5M2MtNGI0OC00MDA2LWI5NzEtMmZiYjVjMDEyOWYzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "The Shape of Water"
                        },
                        new
                        {
                            Id = 59,
                            AverageRating = 8.1m,
                            CreatedAt = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2011,
                            Title = "Harry Potter and the Deathly Hallows: Part 2"
                        },
                        new
                        {
                            Id = 60,
                            AverageRating = 6.9m,
                            CreatedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Four kids travel through a wardrobe to the land of Narnia and learn of their destiny to free it...",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTc0NTUwMTU5OV5BMl5BanBnXkFtZTcwNjAwNzQzMw@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2005,
                            Title = "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = 61,
                            AverageRating = 6.7m,
                            CreatedAt = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzhmODMzYzMtNTM5NS00NDQyLWEyMjYtYzBiYzExYjU0MTJlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2023,
                            Title = "Indiana Jones and the Dial of Destiny"
                        },
                        new
                        {
                            Id = 62,
                            AverageRating = 6.6m,
                            CreatedAt = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Based on Disneyland's theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNDE1MGRlNTQtZjc4ZC00MTI0LWEwY2MtODk1YTM2NmFmYTNmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2021,
                            Title = "Jungle Cruise"
                        },
                        new
                        {
                            Id = 63,
                            AverageRating = 6.1m,
                            CreatedAt = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2022,
                            Title = "The Lost City"
                        },
                        new
                        {
                            Id = 64,
                            AverageRating = 6.3m,
                            CreatedAt = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor Sullivan to recover a fortune amassed by Ferdinand Magellan.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2022,
                            Title = "Uncharted"
                        },
                        new
                        {
                            Id = 65,
                            AverageRating = 6.1m,
                            CreatedAt = new DateTime(2019, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dora, a teenage explorer, leads her friends on an adventure to save her parents and solve the mystery behind a lost city of gold.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOTVhMzYxNjgtYzYwOC00MGIwLWJmZGEtMjgwMzgxMWUwNmRhXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2019,
                            Title = "Dora and the Lost City of Gold"
                        },
                        new
                        {
                            Id = 66,
                            AverageRating = 6.7m,
                            CreatedAt = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOWM0YWMwMDQtMjE5NS00ZTIwLWE1NWEtODViMWZjMWI2OTU3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX1280.jpg",
                            IsDeleted = false,
                            ReleaseYear = 2022,
                            Title = "The Adam Project"
                        });
                });

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 40,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 45,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 50,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 51,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 52,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 53,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 54,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 55,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 55,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 56,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 57,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 57,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 58,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 58,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 59,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 60,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 60,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 61,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 61,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 62,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 62,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 63,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 63,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 64,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 64,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 65,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 65,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 66,
                            GenreId = 11
                        },
                        new
                        {
                            MovieId = 66,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.MovieGenre", b =>
                {
                    b.HasOne("MoviesHub.Services.MoviesAPI.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesHub.Services.MoviesAPI.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MoviesHub.Services.MoviesAPI.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
